#!/usr/bin/bash
cp /etc/hosts /home/gideon/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' /home/gideon/hosts.new
sed -i '2i8.8.8.8 facebook.com' /home/gideon/hosts.new
cp -f /home/gideon/hosts.new /etc/hosts